##### APIs

### root api
GET http://localhost:8000/

### Create new user
POST http://localhost:8000/api/v1/user/register
Content-Type: application/json

{
    "firstName": "Prerana",
    "lastName": "Tamrakar",
    "username": "pre04",
    "email": "user2@example.com",
    "password": "C.ronaldo7",
}

##### Email APIs

### verify user email
PATCH  http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "pin": "645562",
    "email": "user@example.com"
}

### Login User
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "username": "pariwesh7",
    "password": "12345678"
}



### Get user details
GET http://localhost:8000/api/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhcml3ZXNoNyIsImlhdCI6MTY0NjQ4MTc2NCwiZXhwIjoxNjQ2NDgyNjY0fQ.vVmDtVRSza2x5mhlFrAdgWW4H98WkudPp-PhKAwZLUI


### update password
POST http://localhost:8000/api/v1/user/password-update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhcml3ZXNoNyIsImlhdCI6MTY0NDc4NzI1MywiZXhwIjoxNjQ0Nzg4MTUzfQ.l8OJ18j-VTHWLxaeXJV4cBbB4DXdfy0cyBK0IYKAS5g

{
    "currentPassword": "12345678",
  "password": "C.ronaldo7"
}

### reset new password
POST http://localhost:8000/api/v1/user/reset-password
Content-Type: application/json

{
    "otp": 476335,
    "email": "user@gmail.com"
    "newPassword": "Pariwesh.7"
}

### Get Products
GET http://localhost:8000/api/v1/products/


###################################### TOKEN ROUTERS ########################################################

### Get new access token
GET http://localhost:8000/api/v1/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhcml3ZXNoNyIsImlhdCI6MTY0NDQwNDIzMCwiZXhwIjoxNjQ2OTk2MjMwfQ.jqgF_s5Cgef5-THPJKFHhKkM7KwVHjVyjokVNxo7lpM


### User forgot password otp reuqest
POST http://localhost:8000/api/v1/token/request-otp
Content-Type: application/json

{
    "email": "user@gmail.com"

}

###
POST http://localhost:8000/api/v1/cart
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhcml3ZXNoNyIsImlhdCI6MTY0NjAzNjU5MSwiZXhwIjoxNjQ2MDM3NDkxfQ.mArvp1ImAqBDuhnl2-n3QjOi8kjoQz6Awuwp_c5kPMc

###
PATCH http://localhost:8000/api/v1/cart/orderstatus
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhcml3ZXNoNyIsImlhdCI6MTY0Njk3MzAxMCwiZXhwIjoxNjQ3MDU5NDEwfQ.uHn8TuzKoPlRz7QHL6Jet8i0za9aUImR61gJAVgQD9c
###
GET http://localhost:8000/api/v1/order/paid
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhcml3ZXNoNyIsImlhdCI6MTY0Njk3MzAxMCwiZXhwIjoxNjQ3MDU5NDEwfQ.uHn8TuzKoPlRz7QHL6Jet8i0za9aUImR61gJAVgQD9c

###
GET http://localhost:8000/api/v1/payment/create